package seu.lab.dolphin.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOLPHIN_CONTEXT.
 */
public class DolphinContext {

    private Long id;
    /** Not-null value. */
    private String activity_name;
    /** Not-null value. */
    private String device_state;

    public DolphinContext() {
    }

    public DolphinContext(Long id) {
        this.id = id;
    }

    public DolphinContext(Long id, String activity_name, String device_state) {
        this.id = id;
        this.activity_name = activity_name;
        this.device_state = device_state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getActivity_name() {
        return activity_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActivity_name(String activity_name) {
        this.activity_name = activity_name;
    }

    /** Not-null value. */
    public String getDevice_state() {
        return device_state;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDevice_state(String device_state) {
        this.device_state = device_state;
    }

}
