package seu.lab.dolphin.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import seu.lab.dolphin.dao.DolphinContext;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DOLPHIN_CONTEXT.
*/
public class DolphinContextDao extends AbstractDao<DolphinContext, Long> {

    public static final String TABLENAME = "DOLPHIN_CONTEXT";

    /**
     * Properties of entity DolphinContext.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "dolphin_context_id");
        public final static Property Activity_name = new Property(1, String.class, "activity_name", false, "ACTIVITY_NAME");
        public final static Property Device_state = new Property(2, String.class, "device_state", false, "DEVICE_STATE");
    };


    public DolphinContextDao(DaoConfig config) {
        super(config);
    }
    
    public DolphinContextDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DOLPHIN_CONTEXT' (" + //
                "'dolphin_context_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ACTIVITY_NAME' TEXT NOT NULL ," + // 1: activity_name
                "'DEVICE_STATE' TEXT NOT NULL );"); // 2: device_state
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DOLPHIN_CONTEXT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DolphinContext entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getActivity_name());
        stmt.bindString(3, entity.getDevice_state());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DolphinContext readEntity(Cursor cursor, int offset) {
        DolphinContext entity = new DolphinContext( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // activity_name
            cursor.getString(offset + 2) // device_state
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DolphinContext entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setActivity_name(cursor.getString(offset + 1));
        entity.setDevice_state(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DolphinContext entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DolphinContext entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
