package seu.lab.dolphin.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table KEY_EVENT.
 */
public class KeyEvent {

    private Long id;
    private int keycode;

    public KeyEvent() {
    }

    public KeyEvent(Long id) {
        this.id = id;
    }

    public KeyEvent(Long id, int keycode) {
        this.id = id;
        this.keycode = keycode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getKeycode() {
        return keycode;
    }

    public void setKeycode(int keycode) {
        this.keycode = keycode;
    }

}
