package seu.lab.dolphin.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table KEY_EVENT.
 */
public class KeyEvent {

    private Long id;
    /** Not-null value. */
    private String name;
    private int keycode;

    public KeyEvent() {
    }

    public KeyEvent(Long id) {
        this.id = id;
    }

    public KeyEvent(Long id, String name, int keycode) {
        this.id = id;
        this.name = name;
        this.keycode = keycode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getKeycode() {
        return keycode;
    }

    public void setKeycode(int keycode) {
        this.keycode = keycode;
    }

}
