package seu.lab.dolphin.dao;

import seu.lab.dolphin.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MODEL_CONFIG.
 */
public class ModelConfig {

    private Long id;
    /** Not-null value. */
    private String masks;
    /** Not-null value. */
    private String models;
    private Long dolphin_context_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ModelConfigDao myDao;

    private DolphinContext dolphinContext;
    private Long dolphinContext__resolvedKey;


    public ModelConfig() {
    }

    public ModelConfig(Long id) {
        this.id = id;
    }

    public ModelConfig(Long id, String masks, String models, Long dolphin_context_id) {
        this.id = id;
        this.masks = masks;
        this.models = models;
        this.dolphin_context_id = dolphin_context_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getModelConfigDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMasks() {
        return masks;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMasks(String masks) {
        this.masks = masks;
    }

    /** Not-null value. */
    public String getModels() {
        return models;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModels(String models) {
        this.models = models;
    }

    public Long getDolphin_context_id() {
        return dolphin_context_id;
    }

    public void setDolphin_context_id(Long dolphin_context_id) {
        this.dolphin_context_id = dolphin_context_id;
    }

    /** To-one relationship, resolved on first access. */
    public DolphinContext getDolphinContext() {
        Long __key = this.dolphin_context_id;
        if (dolphinContext__resolvedKey == null || !dolphinContext__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DolphinContextDao targetDao = daoSession.getDolphinContextDao();
            DolphinContext dolphinContextNew = targetDao.load(__key);
            synchronized (this) {
                dolphinContext = dolphinContextNew;
            	dolphinContext__resolvedKey = __key;
            }
        }
        return dolphinContext;
    }

    public void setDolphinContext(DolphinContext dolphinContext) {
        synchronized (this) {
            this.dolphinContext = dolphinContext;
            dolphin_context_id = dolphinContext == null ? null : dolphinContext.getId();
            dolphinContext__resolvedKey = dolphin_context_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
