package seu.lab.dolphin.dao;

import seu.lab.dolphin.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MODEL.
 */
public class Model {

    private Long id;
    /** Not-null value. */
    private String model_path;
    /** Not-null value. */
    private String name;
    private long traing_data_set_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ModelDao myDao;

    private TrainingDataset trainingDataset;
    private Long trainingDataset__resolvedKey;


    public Model() {
    }

    public Model(Long id) {
        this.id = id;
    }

    public Model(Long id, String model_path, String name, long traing_data_set_id) {
        this.id = id;
        this.model_path = model_path;
        this.name = name;
        this.traing_data_set_id = traing_data_set_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getModelDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getModel_path() {
        return model_path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModel_path(String model_path) {
        this.model_path = model_path;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public long getTraing_data_set_id() {
        return traing_data_set_id;
    }

    public void setTraing_data_set_id(long traing_data_set_id) {
        this.traing_data_set_id = traing_data_set_id;
    }

    /** To-one relationship, resolved on first access. */
    public TrainingDataset getTrainingDataset() {
        long __key = this.traing_data_set_id;
        if (trainingDataset__resolvedKey == null || !trainingDataset__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TrainingDatasetDao targetDao = daoSession.getTrainingDatasetDao();
            TrainingDataset trainingDatasetNew = targetDao.load(__key);
            synchronized (this) {
                trainingDataset = trainingDatasetNew;
            	trainingDataset__resolvedKey = __key;
            }
        }
        return trainingDataset;
    }

    public void setTrainingDataset(TrainingDataset trainingDataset) {
        if (trainingDataset == null) {
            throw new DaoException("To-one property 'traing_data_set_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.trainingDataset = trainingDataset;
            traing_data_set_id = trainingDataset.getId();
            trainingDataset__resolvedKey = traing_data_set_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
