package seu.lab.dolphin.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MODEL_CONFIG.
 */
public class ModelConfig {

    private Long id;
    /** Not-null value. */
    private String masks;
    /** Not-null value. */
    private String model_ids;

    public ModelConfig() {
    }

    public ModelConfig(Long id) {
        this.id = id;
    }

    public ModelConfig(Long id, String masks, String model_ids) {
        this.id = id;
        this.masks = masks;
        this.model_ids = model_ids;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMasks() {
        return masks;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMasks(String masks) {
        this.masks = masks;
    }

    /** Not-null value. */
    public String getModel_ids() {
        return model_ids;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModel_ids(String model_ids) {
        this.model_ids = model_ids;
    }

}
