package seu.lab.dolphin.dao;

import seu.lab.dolphin.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MODEL.
 */
public class Model {

    private Long id;
    /** Not-null value. */
    private String model_path;
    /** Not-null value. */
    private String name;
    private Long dolphin_context_id;
    private Long training_dataset_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ModelDao myDao;

    private DolphinContext dolphinContext;
    private Long dolphinContext__resolvedKey;

    private TrainingDataset trainingDataset;
    private Long trainingDataset__resolvedKey;


    public Model() {
    }

    public Model(Long id) {
        this.id = id;
    }

    public Model(Long id, String model_path, String name, Long dolphin_context_id, Long training_dataset_id) {
        this.id = id;
        this.model_path = model_path;
        this.name = name;
        this.dolphin_context_id = dolphin_context_id;
        this.training_dataset_id = training_dataset_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getModelDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getModel_path() {
        return model_path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModel_path(String model_path) {
        this.model_path = model_path;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Long getDolphin_context_id() {
        return dolphin_context_id;
    }

    public void setDolphin_context_id(Long dolphin_context_id) {
        this.dolphin_context_id = dolphin_context_id;
    }

    public Long getTraining_dataset_id() {
        return training_dataset_id;
    }

    public void setTraining_dataset_id(Long training_dataset_id) {
        this.training_dataset_id = training_dataset_id;
    }

    /** To-one relationship, resolved on first access. */
    public DolphinContext getDolphinContext() {
        Long __key = this.dolphin_context_id;
        if (dolphinContext__resolvedKey == null || !dolphinContext__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DolphinContextDao targetDao = daoSession.getDolphinContextDao();
            DolphinContext dolphinContextNew = targetDao.load(__key);
            synchronized (this) {
                dolphinContext = dolphinContextNew;
            	dolphinContext__resolvedKey = __key;
            }
        }
        return dolphinContext;
    }

    public void setDolphinContext(DolphinContext dolphinContext) {
        synchronized (this) {
            this.dolphinContext = dolphinContext;
            dolphin_context_id = dolphinContext == null ? null : dolphinContext.getId();
            dolphinContext__resolvedKey = dolphin_context_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public TrainingDataset getTrainingDataset() {
        Long __key = this.training_dataset_id;
        if (trainingDataset__resolvedKey == null || !trainingDataset__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TrainingDatasetDao targetDao = daoSession.getTrainingDatasetDao();
            TrainingDataset trainingDatasetNew = targetDao.load(__key);
            synchronized (this) {
                trainingDataset = trainingDatasetNew;
            	trainingDataset__resolvedKey = __key;
            }
        }
        return trainingDataset;
    }

    public void setTrainingDataset(TrainingDataset trainingDataset) {
        synchronized (this) {
            this.trainingDataset = trainingDataset;
            training_dataset_id = trainingDataset == null ? null : trainingDataset.getId();
            trainingDataset__resolvedKey = training_dataset_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
