package seu.lab.dolphin.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import seu.lab.dolphin.dao.Plugin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLUGIN.
*/
public class PluginDao extends AbstractDao<Plugin, Long> {

    public static final String TABLENAME = "PLUGIN";

    /**
     * Properties of entity Plugin.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "plugin_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Plugin_type = new Property(2, int.class, "plugin_type", false, "PLUGIN_TYPE");
        public final static Property Discription = new Property(3, String.class, "discription", false, "DISCRIPTION");
        public final static Property Icon_path = new Property(4, String.class, "icon_path", false, "ICON_PATH");
    };

    private DaoSession daoSession;


    public PluginDao(DaoConfig config) {
        super(config);
    }
    
    public PluginDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PLUGIN' (" + //
                "'plugin_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'PLUGIN_TYPE' INTEGER NOT NULL ," + // 2: plugin_type
                "'DISCRIPTION' TEXT NOT NULL ," + // 3: discription
                "'ICON_PATH' TEXT NOT NULL );"); // 4: icon_path
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLUGIN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Plugin entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getPlugin_type());
        stmt.bindString(4, entity.getDiscription());
        stmt.bindString(5, entity.getIcon_path());
    }

    @Override
    protected void attachEntity(Plugin entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Plugin readEntity(Cursor cursor, int offset) {
        Plugin entity = new Plugin( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // plugin_type
            cursor.getString(offset + 3), // discription
            cursor.getString(offset + 4) // icon_path
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Plugin entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setPlugin_type(cursor.getInt(offset + 2));
        entity.setDiscription(cursor.getString(offset + 3));
        entity.setIcon_path(cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Plugin entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Plugin entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
