package seu.lab.dolphin.dao;

import seu.lab.dolphin.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RAW_GESTURE_DATA.
 */
public class RawGestureData {

    private Long id;
    private byte[] data;
    private long gesture_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient RawGestureDataDao myDao;

    private Gesture gesture;
    private Long gesture__resolvedKey;


    public RawGestureData() {
    }

    public RawGestureData(Long id) {
        this.id = id;
    }

    public RawGestureData(Long id, byte[] data, long gesture_id) {
        this.id = id;
        this.data = data;
        this.gesture_id = gesture_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRawGestureDataDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    public long getGesture_id() {
        return gesture_id;
    }

    public void setGesture_id(long gesture_id) {
        this.gesture_id = gesture_id;
    }

    /** To-one relationship, resolved on first access. */
    public Gesture getGesture() {
        long __key = this.gesture_id;
        if (gesture__resolvedKey == null || !gesture__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            GestureDao targetDao = daoSession.getGestureDao();
            Gesture gestureNew = targetDao.load(__key);
            synchronized (this) {
                gesture = gestureNew;
            	gesture__resolvedKey = __key;
            }
        }
        return gesture;
    }

    public void setGesture(Gesture gesture) {
        if (gesture == null) {
            throw new DaoException("To-one property 'gesture_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.gesture = gesture;
            gesture_id = gesture.getId();
            gesture__resolvedKey = gesture_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
